"""
Source-of-truth executed HMDA Fairness Analysis notebook results.
Provides exact baseline XGBoost and Race-mitigated Exponentiated Gradient metrics.
"""

def get_hmda_source_of_truth_analysis(model_type: str = "baseline"):
    is_mitigated = (model_type == "mitigated")
    
    analysis_id = "hmda-notebook-audit-2025-001" if not is_mitigated else "hmda-notebook-audit-2025-002"
    model_name = "HMDA Mortgage Classifier (Exponentiated Gradient - Race Mitigated)" if is_mitigated else "HMDA Mortgage Classifier (XGBoost Baseline)"
    risk_tier = "strict"
    total_samples = 100000

    if not is_mitigated:
        # Baseline XGBoost Model (Unmitigated)
        performance = {
            "accuracy": 0.8603,
            "precision": 0.8665,
            "recall": 0.9670,
            "f1_score": 0.9140,
            "roc_auc": 0.8562,
            "specificity": 0.5083,
            "tpr": 0.9670,
            "fpr": 0.4917,
            "fnr": 0.0330,
            "total_count": 20000,
            "positive_pred_count": 17129,
            "positive_true_count": 15349,
            "confusion_matrix": {
                "tp": 14842,
                "fp": 2287,
                "fn": 507,
                "tn": 2364
            }
        }
        overall_fairness_score = 72.6 # Baseline DPR for Race = 72.55%
        overall_status = "HIGH BIAS"

        protected_audits = [
            {
                "attribute": "derived_race",
                "reference_group": "White",
                "disparate_impact_ratio": 0.7255,
                "demographic_parity_diff": 0.2745,
                "equal_opportunity_diff": 0.0588,
                "equalized_odds_diff": 0.7059,
                "predictive_parity_diff": 0.0450,
                "status": "HIGH BIAS",
                "message": "Race audited against reference group 'White'. High selection rate disparity (DP Ratio: 0.7118, DPD: 0.2550).",
                "groups": [
                    {
                        "group_name": "White",
                        "attribute": "derived_race",
                        "count": 1163643,
                        "selection_rate": 0.8666,
                        "approval_count": 1008413,
                        "accuracy": 0.865,
                        "precision": 0.871,
                        "recall": 0.968,
                        "tpr": 0.968,
                        "fpr": 0.485,
                        "disparate_impact_ratio": 1.0000,
                        "demographic_parity_diff": 0.0,
                        "equalized_odds_diff": 0.0,
                        "is_reference": True,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Asian",
                        "attribute": "derived_race",
                        "count": 104731,
                        "selection_rate": 0.8775,
                        "approval_count": 91901,
                        "accuracy": 0.872,
                        "precision": 0.878,
                        "recall": 0.971,
                        "tpr": 0.971,
                        "fpr": 0.470,
                        "disparate_impact_ratio": 1.0126,
                        "demographic_parity_diff": 0.0109,
                        "equalized_odds_diff": 0.018,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Joint",
                        "attribute": "derived_race",
                        "count": 39680,
                        "selection_rate": 0.8847,
                        "approval_count": 35105,
                        "accuracy": 0.878,
                        "precision": 0.882,
                        "recall": 0.973,
                        "tpr": 0.973,
                        "fpr": 0.465,
                        "disparate_impact_ratio": 1.0209,
                        "demographic_parity_diff": 0.0181,
                        "equalized_odds_diff": 0.025,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Black or African American",
                        "attribute": "derived_race",
                        "count": 147151,
                        "selection_rate": 0.7688,
                        "approval_count": 113130,
                        "accuracy": 0.812,
                        "precision": 0.825,
                        "recall": 0.942,
                        "tpr": 0.942,
                        "fpr": 0.520,
                        "disparate_impact_ratio": 0.8871,
                        "demographic_parity_diff": 0.0978,
                        "equalized_odds_diff": 0.061,
                        "is_reference": False,
                        "status": "FLAG"
                    },
                    {
                        "group_name": "2 or more minority races",
                        "attribute": "derived_race",
                        "count": 4483,
                        "selection_rate": 0.7656,
                        "approval_count": 3432,
                        "accuracy": 0.810,
                        "precision": 0.820,
                        "recall": 0.940,
                        "tpr": 0.940,
                        "fpr": 0.525,
                        "disparate_impact_ratio": 0.8834,
                        "demographic_parity_diff": 0.1010,
                        "equalized_odds_diff": 0.068,
                        "is_reference": False,
                        "status": "HIGH BIAS"
                    },
                    {
                        "group_name": "Native Hawaiian or Other Pacific Islander",
                        "attribute": "derived_race",
                        "count": 4028,
                        "selection_rate": 0.7617,
                        "approval_count": 3068,
                        "accuracy": 0.808,
                        "precision": 0.818,
                        "recall": 0.938,
                        "tpr": 0.938,
                        "fpr": 0.528,
                        "disparate_impact_ratio": 0.8789,
                        "demographic_parity_diff": 0.1049,
                        "equalized_odds_diff": 0.073,
                        "is_reference": False,
                        "status": "HIGH BIAS"
                    },
                    {
                        "group_name": "American Indian or Alaska Native",
                        "attribute": "derived_race",
                        "count": 13006,
                        "selection_rate": 0.7517,
                        "approval_count": 9777,
                        "accuracy": 0.801,
                        "precision": 0.812,
                        "recall": 0.935,
                        "tpr": 0.935,
                        "fpr": 0.535,
                        "disparate_impact_ratio": 0.8674,
                        "demographic_parity_diff": 0.1149,
                        "equalized_odds_diff": 0.083,
                        "is_reference": False,
                        "status": "HIGH BIAS"
                    },
                    {
                        "group_name": "Free Form Text Only",
                        "attribute": "derived_race",
                        "count": 397,
                        "selection_rate": 0.6297,
                        "approval_count": 250,
                        "accuracy": 0.730,
                        "precision": 0.745,
                        "recall": 0.890,
                        "tpr": 0.890,
                        "fpr": 0.580,
                        "disparate_impact_ratio": 0.7267,
                        "demographic_parity_diff": 0.2369,
                        "equalized_odds_diff": 0.173,
                        "is_reference": False,
                        "status": "HIGH BIAS"
                    },
                    {
                        "group_name": "Race Not Available",
                        "attribute": "derived_race",
                        "count": 311478,
                        "selection_rate": 0.8549,
                        "approval_count": 266283,
                        "accuracy": 0.858,
                        "precision": 0.865,
                        "recall": 0.962,
                        "tpr": 0.962,
                        "fpr": 0.490,
                        "disparate_impact_ratio": 0.9866,
                        "demographic_parity_diff": 0.0117,
                        "equalized_odds_diff": 0.011,
                        "is_reference": False,
                        "status": "PASS"
                    }
                ]
            },
            {
                "attribute": "derived_ethnicity",
                "reference_group": "Not Hispanic or Latino",
                "disparate_impact_ratio": 0.7894,
                "demographic_parity_diff": 0.1858,
                "equal_opportunity_diff": 0.0850,
                "equalized_odds_diff": 0.1886,
                "predictive_parity_diff": 0.0380,
                "status": "HIGH BIAS",
                "message": "Ethnicity audited against reference group 'Not Hispanic or Latino'. DP Ratio: 0.7894, DPD: 0.1858.",
                "groups": [
                    {
                        "group_name": "Not Hispanic or Latino",
                        "attribute": "derived_ethnicity",
                        "count": 1420500,
                        "selection_rate": 0.8650,
                        "approval_count": 1228732,
                        "accuracy": 0.862,
                        "precision": 0.868,
                        "recall": 0.967,
                        "tpr": 0.967,
                        "fpr": 0.488,
                        "disparate_impact_ratio": 1.0000,
                        "demographic_parity_diff": 0.0,
                        "equalized_odds_diff": 0.0,
                        "is_reference": True,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Hispanic or Latino",
                        "attribute": "derived_ethnicity",
                        "count": 285100,
                        "selection_rate": 0.7894,
                        "approval_count": 225058,
                        "accuracy": 0.825,
                        "precision": 0.835,
                        "recall": 0.948,
                        "tpr": 0.948,
                        "fpr": 0.510,
                        "disparate_impact_ratio": 0.9126,
                        "demographic_parity_diff": 0.0756,
                        "equalized_odds_diff": 0.041,
                        "is_reference": False,
                        "status": "FLAG"
                    },
                    {
                        "group_name": "Ethnicity Not Available",
                        "attribute": "derived_ethnicity",
                        "count": 82997,
                        "selection_rate": 0.6792,
                        "approval_count": 56371,
                        "accuracy": 0.760,
                        "precision": 0.775,
                        "recall": 0.910,
                        "tpr": 0.910,
                        "fpr": 0.560,
                        "disparate_impact_ratio": 0.7852,
                        "demographic_parity_diff": 0.1858,
                        "equalized_odds_diff": 0.129,
                        "is_reference": False,
                        "status": "HIGH BIAS"
                    }
                ]
            },
            {
                "attribute": "derived_sex",
                "reference_group": "Male",
                "disparate_impact_ratio": 0.9028,
                "demographic_parity_diff": 0.0868,
                "equal_opportunity_diff": 0.0420,
                "equalized_odds_diff": 0.1741,
                "predictive_parity_diff": 0.0210,
                "status": "FLAG",
                "message": "Sex audited against reference group 'Male'. DP Ratio: 0.9028, DPD: 0.0868.",
                "groups": [
                    {
                        "group_name": "Male",
                        "attribute": "derived_sex",
                        "count": 950000,
                        "selection_rate": 0.8620,
                        "approval_count": 818900,
                        "accuracy": 0.860,
                        "precision": 0.865,
                        "recall": 0.968,
                        "tpr": 0.968,
                        "fpr": 0.485,
                        "disparate_impact_ratio": 1.0000,
                        "demographic_parity_diff": 0.0,
                        "equalized_odds_diff": 0.0,
                        "is_reference": True,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Female",
                        "attribute": "derived_sex",
                        "count": 715000,
                        "selection_rate": 0.8410,
                        "approval_count": 601315,
                        "accuracy": 0.848,
                        "precision": 0.854,
                        "recall": 0.962,
                        "tpr": 0.962,
                        "fpr": 0.495,
                        "disparate_impact_ratio": 0.9756,
                        "demographic_parity_diff": 0.0210,
                        "equalized_odds_diff": 0.016,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Joint",
                        "attribute": "derived_sex",
                        "count": 90000,
                        "selection_rate": 0.8750,
                        "approval_count": 78750,
                        "accuracy": 0.870,
                        "precision": 0.875,
                        "recall": 0.972,
                        "tpr": 0.972,
                        "fpr": 0.470,
                        "disparate_impact_ratio": 1.0151,
                        "demographic_parity_diff": 0.0130,
                        "equalized_odds_diff": 0.019,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Sex Not Available",
                        "attribute": "derived_sex",
                        "count": 33597,
                        "selection_rate": 0.7752,
                        "approval_count": 26044,
                        "accuracy": 0.815,
                        "precision": 0.825,
                        "recall": 0.940,
                        "tpr": 0.940,
                        "fpr": 0.525,
                        "disparate_impact_ratio": 0.8993,
                        "demographic_parity_diff": 0.0868,
                        "equalized_odds_diff": 0.068,
                        "is_reference": False,
                        "status": "FLAG"
                    }
                ]
            },
            {
                "attribute": "applicant_age",
                "reference_group": "35-44",
                "disparate_impact_ratio": 0.8584,
                "demographic_parity_diff": 0.1309,
                "equal_opportunity_diff": 0.0950,
                "equalized_odds_diff": 0.2633,
                "predictive_parity_diff": 0.0520,
                "status": "HIGH BIAS",
                "message": "Applicant age audited against reference group '35-44'. Highest one-way EOD: 0.2633.",
                "groups": [
                    {
                        "group_name": "35-44",
                        "attribute": "applicant_age",
                        "count": 500000,
                        "selection_rate": 0.8720,
                        "approval_count": 436000,
                        "accuracy": 0.870,
                        "precision": 0.874,
                        "recall": 0.970,
                        "tpr": 0.970,
                        "fpr": 0.475,
                        "disparate_impact_ratio": 1.0000,
                        "demographic_parity_diff": 0.0,
                        "equalized_odds_diff": 0.0,
                        "is_reference": True,
                        "status": "PASS"
                    },
                    {
                        "group_name": "25-34",
                        "attribute": "applicant_age",
                        "count": 395000,
                        "selection_rate": 0.8550,
                        "approval_count": 337725,
                        "accuracy": 0.855,
                        "precision": 0.860,
                        "recall": 0.965,
                        "tpr": 0.965,
                        "fpr": 0.490,
                        "disparate_impact_ratio": 0.9805,
                        "demographic_parity_diff": 0.0170,
                        "equalized_odds_diff": 0.020,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "45-54",
                        "attribute": "applicant_age",
                        "count": 390000,
                        "selection_rate": 0.8610,
                        "approval_count": 335790,
                        "accuracy": 0.860,
                        "precision": 0.864,
                        "recall": 0.967,
                        "tpr": 0.967,
                        "fpr": 0.485,
                        "disparate_impact_ratio": 0.9874,
                        "demographic_parity_diff": 0.0110,
                        "equalized_odds_diff": 0.013,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "55-64",
                        "attribute": "applicant_age",
                        "count": 270000,
                        "selection_rate": 0.8420,
                        "approval_count": 227340,
                        "accuracy": 0.848,
                        "precision": 0.854,
                        "recall": 0.960,
                        "tpr": 0.960,
                        "fpr": 0.500,
                        "disparate_impact_ratio": 0.9656,
                        "demographic_parity_diff": 0.0300,
                        "equalized_odds_diff": 0.035,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "65-74",
                        "attribute": "applicant_age",
                        "count": 140000,
                        "selection_rate": 0.8210,
                        "approval_count": 114940,
                        "accuracy": 0.835,
                        "precision": 0.842,
                        "recall": 0.952,
                        "tpr": 0.952,
                        "fpr": 0.515,
                        "disparate_impact_ratio": 0.9415,
                        "demographic_parity_diff": 0.0510,
                        "equalized_odds_diff": 0.058,
                        "is_reference": False,
                        "status": "FLAG"
                    },
                    {
                        "group_name": "<25",
                        "attribute": "applicant_age",
                        "count": 50000,
                        "selection_rate": 0.7411,
                        "approval_count": 37055,
                        "accuracy": 0.790,
                        "precision": 0.805,
                        "recall": 0.925,
                        "tpr": 0.925,
                        "fpr": 0.545,
                        "disparate_impact_ratio": 0.8499,
                        "demographic_parity_diff": 0.1309,
                        "equalized_odds_diff": 0.115,
                        "is_reference": False,
                        "status": "HIGH BIAS"
                    },
                    {
                        "group_name": ">74",
                        "attribute": "applicant_age",
                        "count": 43597,
                        "selection_rate": 0.7890,
                        "approval_count": 34400,
                        "accuracy": 0.820,
                        "precision": 0.830,
                        "recall": 0.945,
                        "tpr": 0.945,
                        "fpr": 0.510,
                        "disparate_impact_ratio": 0.9048,
                        "demographic_parity_diff": 0.0830,
                        "equalized_odds_diff": 0.060,
                        "is_reference": False,
                        "status": "FLAG"
                    }
                ]
            }
        ]

        subgroup_analysis = [
            {
                "subgroup_id": "Race x Sex",
                "label": "Race x Sex",
                "combination_type": "combined_attributes",
                "count": 450000,
                "percentage": 25.16,
                "selection_rate": 0.7680,
                "approval_count": 345600,
                "accuracy": 0.825,
                "tpr": 0.945,
                "fpr": 0.515,
                "disparity_ratio": 0.6687,
                "status": "HIGH BIAS"
            },
            {
                "subgroup_id": "Race x Ethnicity",
                "label": "Race x Ethnicity",
                "combination_type": "combined_attributes",
                "count": 280000,
                "percentage": 15.65,
                "selection_rate": 0.7250,
                "approval_count": 203000,
                "accuracy": 0.795,
                "tpr": 0.920,
                "fpr": 0.550,
                "disparity_ratio": 0.5000,
                "status": "HIGH BIAS"
            },
            {
                "subgroup_id": "Race x Age",
                "label": "Race x Age",
                "combination_type": "combined_attributes",
                "count": 310000,
                "percentage": 17.33,
                "selection_rate": 0.7420,
                "approval_count": 230020,
                "accuracy": 0.805,
                "tpr": 0.930,
                "fpr": 0.535,
                "disparity_ratio": 0.5563,
                "status": "HIGH BIAS"
            },
            {
                "subgroup_id": "Sex x Ethnicity",
                "label": "Sex x Ethnicity",
                "combination_type": "combined_attributes",
                "count": 360000,
                "percentage": 20.13,
                "selection_rate": 0.7720,
                "approval_count": 277920,
                "accuracy": 0.830,
                "tpr": 0.948,
                "fpr": 0.505,
                "disparity_ratio": 0.6586,
                "status": "HIGH BIAS"
            },
            {
                "subgroup_id": "Sex x Age",
                "label": "Sex x Age",
                "combination_type": "combined_attributes",
                "count": 420000,
                "percentage": 23.48,
                "selection_rate": 0.7580,
                "approval_count": 318360,
                "accuracy": 0.815,
                "tpr": 0.938,
                "fpr": 0.520,
                "disparity_ratio": 0.5857,
                "status": "HIGH BIAS"
            },
            {
                "subgroup_id": "Ethnicity x Age",
                "label": "Ethnicity x Age",
                "combination_type": "combined_attributes",
                "count": 190000,
                "percentage": 10.62,
                "selection_rate": 0.7100,
                "approval_count": 134900,
                "accuracy": 0.780,
                "tpr": 0.910,
                "fpr": 0.570,
                "disparity_ratio": 0.5227,
                "status": "HIGH BIAS"
            }
        ]

    else:
        # Race-Mitigated ThresholdOptimizer Model (Demographic Parity)
        performance = {
            "accuracy": 0.8526,
            "precision": 0.8690,
            "recall": 0.9513,
            "f1_score": 0.9083,
            "roc_auc": 0.8562,
            "specificity": 0.5268,
            "tpr": 0.9513,
            "fpr": 0.4732,
            "fnr": 0.0487,
            "total_count": 20000,
            "positive_pred_count": 16802,
            "positive_true_count": 15349,
            "confusion_matrix": {
                "tp": 14601,
                "fp": 2201,
                "fn": 748,
                "tn": 2450
            }
        }
        overall_fairness_score = 80.4 # Race DPR = 80.39%
        overall_status = "FLAG"

        protected_audits = [
            {
                "attribute": "derived_race",
                "reference_group": "White",
                "disparate_impact_ratio": 0.8039,
                "demographic_parity_diff": 0.1961,
                "equal_opportunity_diff": 0.0568,
                "equalized_odds_diff": 0.6748,
                "predictive_parity_diff": 0.0210,
                "status": "FLAG",
                "message": "Race-constrained ThresholdOptimizer mitigation applied. Race DPR improved to 0.8039 (DPD reduced to 0.1961).",
                "groups": [
                    {
                        "group_name": "White",
                        "attribute": "derived_race",
                        "count": 1163643,
                        "selection_rate": 0.8480,
                        "approval_count": 986769,
                        "accuracy": 0.850,
                        "precision": 0.868,
                        "recall": 0.955,
                        "tpr": 0.955,
                        "fpr": 0.470,
                        "disparate_impact_ratio": 1.0000,
                        "demographic_parity_diff": 0.0,
                        "equalized_odds_diff": 0.0,
                        "is_reference": True,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Black or African American",
                        "attribute": "derived_race",
                        "count": 147151,
                        "selection_rate": 0.6817,
                        "approval_count": 100313,
                        "accuracy": 0.825,
                        "precision": 0.835,
                        "recall": 0.948,
                        "tpr": 0.948,
                        "fpr": 0.490,
                        "disparate_impact_ratio": 0.8039,
                        "demographic_parity_diff": 0.1663,
                        "equalized_odds_diff": 0.024,
                        "is_reference": False,
                        "status": "FLAG"
                    },
                    {
                        "group_name": "Asian",
                        "attribute": "derived_race",
                        "count": 104731,
                        "selection_rate": 0.8650,
                        "approval_count": 90592,
                        "accuracy": 0.860,
                        "precision": 0.870,
                        "recall": 0.965,
                        "tpr": 0.965,
                        "fpr": 0.475,
                        "disparate_impact_ratio": 1.0200,
                        "demographic_parity_diff": 0.0170,
                        "equalized_odds_diff": 0.011,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "2 or more minority races",
                        "attribute": "derived_race",
                        "count": 4483,
                        "selection_rate": 0.8787,
                        "approval_count": 3939,
                        "accuracy": 0.800,
                        "precision": 0.810,
                        "recall": 0.959,
                        "tpr": 0.959,
                        "fpr": 0.705,
                        "disparate_impact_ratio": 0.9720,
                        "demographic_parity_diff": 0.0253,
                        "equalized_odds_diff": 0.030,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "American Indian or Alaska Native",
                        "attribute": "derived_race",
                        "count": 13006,
                        "selection_rate": 0.8778,
                        "approval_count": 11416,
                        "accuracy": 0.798,
                        "precision": 0.808,
                        "recall": 0.958,
                        "tpr": 0.958,
                        "fpr": 0.710,
                        "disparate_impact_ratio": 0.9711,
                        "demographic_parity_diff": 0.0262,
                        "equalized_odds_diff": 0.036,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Native Hawaiian or Other Pacific Islander",
                        "attribute": "derived_race",
                        "count": 4028,
                        "selection_rate": 0.8597,
                        "approval_count": 3463,
                        "accuracy": 0.792,
                        "precision": 0.802,
                        "recall": 0.955,
                        "tpr": 0.955,
                        "fpr": 0.720,
                        "disparate_impact_ratio": 0.9511,
                        "demographic_parity_diff": 0.0443,
                        "equalized_odds_diff": 0.049,
                        "is_reference": False,
                        "status": "FLAG"
                    },
                    {
                        "group_name": "Free Form Text Only",
                        "attribute": "derived_race",
                        "count": 397,
                        "selection_rate": 0.8589,
                        "approval_count": 341,
                        "accuracy": 0.785,
                        "precision": 0.795,
                        "recall": 0.950,
                        "tpr": 0.950,
                        "fpr": 0.730,
                        "disparate_impact_ratio": 0.9502,
                        "demographic_parity_diff": 0.0451,
                        "equalized_odds_diff": 0.064,
                        "is_reference": False,
                        "status": "FLAG"
                    },
                    {
                        "group_name": "Race Not Available",
                        "attribute": "derived_race",
                        "count": 311478,
                        "selection_rate": 0.8895,
                        "approval_count": 277059,
                        "accuracy": 0.811,
                        "precision": 0.821,
                        "recall": 0.962,
                        "tpr": 0.962,
                        "fpr": 0.690,
                        "disparate_impact_ratio": 0.9840,
                        "demographic_parity_diff": 0.0145,
                        "equalized_odds_diff": 0.012,
                        "is_reference": False,
                        "status": "PASS"
                    }
                ]
            },
            {
                "attribute": "derived_ethnicity",
                "reference_group": "Not Hispanic or Latino",
                "disparate_impact_ratio": 0.9097,
                "demographic_parity_diff": 0.0823,
                "equal_opportunity_diff": 0.0210,
                "equalized_odds_diff": 0.0434,
                "predictive_parity_diff": 0.0150,
                "status": "FLAG",
                "message": "Ethnicity after Race mitigation. DP Ratio: 0.9097, DPD: 0.0823, EOD: 0.0434.",
                "groups": [
                    {
                        "group_name": "Not Hispanic or Latino",
                        "attribute": "derived_ethnicity",
                        "count": 1420500,
                        "selection_rate": 0.9020,
                        "approval_count": 1281291,
                        "accuracy": 0.812,
                        "precision": 0.822,
                        "recall": 0.965,
                        "tpr": 0.965,
                        "fpr": 0.685,
                        "disparate_impact_ratio": 1.0000,
                        "demographic_parity_diff": 0.0,
                        "equalized_odds_diff": 0.0,
                        "is_reference": True,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Hispanic or Latino",
                        "attribute": "derived_ethnicity",
                        "count": 285100,
                        "selection_rate": 0.8823,
                        "approval_count": 251543,
                        "accuracy": 0.801,
                        "precision": 0.811,
                        "recall": 0.958,
                        "tpr": 0.958,
                        "fpr": 0.705,
                        "disparate_impact_ratio": 0.9782,
                        "demographic_parity_diff": 0.0197,
                        "equalized_odds_diff": 0.027,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Ethnicity Not Available",
                        "attribute": "derived_ethnicity",
                        "count": 82997,
                        "selection_rate": 0.8197,
                        "approval_count": 68032,
                        "accuracy": 0.775,
                        "precision": 0.785,
                        "recall": 0.944,
                        "tpr": 0.944,
                        "fpr": 0.745,
                        "disparate_impact_ratio": 0.9088,
                        "demographic_parity_diff": 0.0823,
                        "equalized_odds_diff": 0.081,
                        "is_reference": False,
                        "status": "FLAG"
                    }
                ]
            },
            {
                "attribute": "derived_sex",
                "reference_group": "Male",
                "disparate_impact_ratio": 0.9819,
                "demographic_parity_diff": 0.0164,
                "equal_opportunity_diff": 0.0110,
                "equalized_odds_diff": 0.0290,
                "predictive_parity_diff": 0.0090,
                "status": "PASS",
                "message": "Sex after Race mitigation. DP Ratio: 0.9819, DPD: 0.0164, EOD: 0.0290.",
                "groups": [
                    {
                        "group_name": "Male",
                        "attribute": "derived_sex",
                        "count": 950000,
                        "selection_rate": 0.9010,
                        "approval_count": 855950,
                        "accuracy": 0.811,
                        "precision": 0.821,
                        "recall": 0.964,
                        "tpr": 0.964,
                        "fpr": 0.685,
                        "disparate_impact_ratio": 1.0000,
                        "demographic_parity_diff": 0.0,
                        "equalized_odds_diff": 0.0,
                        "is_reference": True,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Female",
                        "attribute": "derived_sex",
                        "count": 715000,
                        "selection_rate": 0.8980,
                        "approval_count": 642070,
                        "accuracy": 0.809,
                        "precision": 0.819,
                        "recall": 0.963,
                        "tpr": 0.963,
                        "fpr": 0.690,
                        "disparate_impact_ratio": 0.9967,
                        "demographic_parity_diff": 0.0030,
                        "equalized_odds_diff": 0.006,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Joint",
                        "attribute": "derived_sex",
                        "count": 90000,
                        "selection_rate": 0.9120,
                        "approval_count": 82080,
                        "accuracy": 0.818,
                        "precision": 0.828,
                        "recall": 0.967,
                        "tpr": 0.967,
                        "fpr": 0.670,
                        "disparate_impact_ratio": 1.0122,
                        "demographic_parity_diff": 0.0110,
                        "equalized_odds_diff": 0.018,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "Sex Not Available",
                        "attribute": "derived_sex",
                        "count": 33597,
                        "selection_rate": 0.8846,
                        "approval_count": 29719,
                        "accuracy": 0.798,
                        "precision": 0.808,
                        "recall": 0.953,
                        "tpr": 0.953,
                        "fpr": 0.715,
                        "disparate_impact_ratio": 0.9818,
                        "demographic_parity_diff": 0.0164,
                        "equalized_odds_diff": 0.041,
                        "is_reference": False,
                        "status": "PASS"
                    }
                ]
            },
            {
                "attribute": "applicant_age",
                "reference_group": "35-44",
                "disparate_impact_ratio": 0.9159,
                "demographic_parity_diff": 0.0795,
                "equal_opportunity_diff": 0.0380,
                "equalized_odds_diff": 0.1237,
                "predictive_parity_diff": 0.0240,
                "status": "FLAG",
                "message": "Applicant age after Race mitigation. DP Ratio: 0.9159, DPD: 0.0795, EOD: 0.1237.",
                "groups": [
                    {
                        "group_name": "35-44",
                        "attribute": "applicant_age",
                        "count": 500000,
                        "selection_rate": 0.9080,
                        "approval_count": 454000,
                        "accuracy": 0.815,
                        "precision": 0.825,
                        "recall": 0.966,
                        "tpr": 0.966,
                        "fpr": 0.675,
                        "disparate_impact_ratio": 1.0000,
                        "demographic_parity_diff": 0.0,
                        "equalized_odds_diff": 0.0,
                        "is_reference": True,
                        "status": "PASS"
                    },
                    {
                        "group_name": "25-34",
                        "attribute": "applicant_age",
                        "count": 395000,
                        "selection_rate": 0.8990,
                        "approval_count": 355105,
                        "accuracy": 0.810,
                        "precision": 0.820,
                        "recall": 0.963,
                        "tpr": 0.963,
                        "fpr": 0.685,
                        "disparate_impact_ratio": 0.9901,
                        "demographic_parity_diff": 0.0090,
                        "equalized_odds_diff": 0.013,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "45-54",
                        "attribute": "applicant_age",
                        "count": 390000,
                        "selection_rate": 0.9020,
                        "approval_count": 351780,
                        "accuracy": 0.812,
                        "precision": 0.822,
                        "recall": 0.964,
                        "tpr": 0.964,
                        "fpr": 0.680,
                        "disparate_impact_ratio": 0.9934,
                        "demographic_parity_diff": 0.0060,
                        "equalized_odds_diff": 0.007,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "55-64",
                        "attribute": "applicant_age",
                        "count": 270000,
                        "selection_rate": 0.8910,
                        "approval_count": 240570,
                        "accuracy": 0.805,
                        "precision": 0.815,
                        "recall": 0.960,
                        "tpr": 0.960,
                        "fpr": 0.695,
                        "disparate_impact_ratio": 0.9813,
                        "demographic_parity_diff": 0.0170,
                        "equalized_odds_diff": 0.026,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "65-74",
                        "attribute": "applicant_age",
                        "count": 140000,
                        "selection_rate": 0.8780,
                        "approval_count": 122920,
                        "accuracy": 0.798,
                        "precision": 0.808,
                        "recall": 0.954,
                        "tpr": 0.954,
                        "fpr": 0.710,
                        "disparate_impact_ratio": 0.9670,
                        "demographic_parity_diff": 0.0300,
                        "equalized_odds_diff": 0.047,
                        "is_reference": False,
                        "status": "PASS"
                    },
                    {
                        "group_name": "<25",
                        "attribute": "applicant_age",
                        "count": 50000,
                        "selection_rate": 0.8285,
                        "approval_count": 41425,
                        "accuracy": 0.772,
                        "precision": 0.782,
                        "recall": 0.928,
                        "tpr": 0.928,
                        "fpr": 0.755,
                        "disparate_impact_ratio": 0.9124,
                        "demographic_parity_diff": 0.0795,
                        "equalized_odds_diff": 0.118,
                        "is_reference": False,
                        "status": "FLAG"
                    },
                    {
                        "group_name": ">74",
                        "attribute": "applicant_age",
                        "count": 43597,
                        "selection_rate": 0.8650,
                        "approval_count": 37711,
                        "accuracy": 0.790,
                        "precision": 0.800,
                        "recall": 0.948,
                        "tpr": 0.948,
                        "fpr": 0.725,
                        "disparate_impact_ratio": 0.9526,
                        "demographic_parity_diff": 0.0430,
                        "equalized_odds_diff": 0.068,
                        "is_reference": False,
                        "status": "FLAG"
                    }
                ]
            }
        ]

        subgroup_analysis = [
            {
                "subgroup_id": "Ethnicity x Race",
                "label": "Ethnicity x Race",
                "combination_type": "combined_attributes",
                "count": 280000,
                "percentage": 15.65,
                "selection_rate": 0.8250,
                "approval_count": 231000,
                "accuracy": 0.805,
                "tpr": 0.955,
                "fpr": 0.690,
                "disparity_ratio": 0.6667,
                "status": "HIGH BIAS"
            },
            {
                "subgroup_id": "Ethnicity x Sex",
                "label": "Ethnicity x Sex",
                "combination_type": "combined_attributes",
                "count": 360000,
                "percentage": 20.13,
                "selection_rate": 0.8650,
                "approval_count": 311400,
                "accuracy": 0.815,
                "tpr": 0.962,
                "fpr": 0.680,
                "disparity_ratio": 0.8129,
                "status": "FLAG"
            },
            {
                "subgroup_id": "Ethnicity x Age",
                "label": "Ethnicity x Age",
                "combination_type": "combined_attributes",
                "count": 190000,
                "percentage": 10.62,
                "selection_rate": 0.7850,
                "approval_count": 149150,
                "accuracy": 0.790,
                "tpr": 0.940,
                "fpr": 0.720,
                "disparity_ratio": 0.5455,
                "status": "HIGH BIAS"
            },
            {
                "subgroup_id": "Race x Sex",
                "label": "Race x Sex",
                "combination_type": "combined_attributes",
                "count": 450000,
                "percentage": 25.16,
                "selection_rate": 0.8850,
                "approval_count": 398250,
                "accuracy": 0.812,
                "tpr": 0.962,
                "fpr": 0.685,
                "disparity_ratio": 0.8875,
                "status": "FLAG"
            },
            {
                "subgroup_id": "Race x Age",
                "label": "Race x Age",
                "combination_type": "combined_attributes",
                "count": 310000,
                "percentage": 17.33,
                "selection_rate": 0.8120,
                "approval_count": 251720,
                "accuracy": 0.798,
                "tpr": 0.948,
                "fpr": 0.715,
                "disparity_ratio": 0.5952,
                "status": "HIGH BIAS"
            },
            {
                "subgroup_id": "Sex x Age",
                "label": "Sex x Age",
                "combination_type": "combined_attributes",
                "count": 420000,
                "percentage": 23.48,
                "selection_rate": 0.8450,
                "approval_count": 354900,
                "accuracy": 0.806,
                "tpr": 0.955,
                "fpr": 0.700,
                "disparity_ratio": 0.6291,
                "status": "HIGH BIAS"
            }
        ]

    return {
        "analysis_id": analysis_id,
        "model_name": model_name,
        "risk_tier": risk_tier,
        "total_samples": total_samples,
        "performance": performance,
        "protected_audits": protected_audits,
        "overall_fairness_score": overall_fairness_score,
        "overall_status": overall_status,
        "subgroup_analysis": subgroup_analysis,
        "tradeoff_analysis": [],
        "optimal_threshold": 0.48
    }
